import math

import pathplannerlib.config
import wpimath.geometry
import wpimath.kinematics
import wpimath.units


class Constants:
    def __init__(self):
        # --- Controllers ---
        self.swerveController = 0
        self.shooterController = 1

        # --- Elevator --
        self.ElevatorSpeedPercentage = 0.4

        # --- Shooter ---
        self.shooterKA = wpimath.units.rotationsToRadians(0.1)
        self.shooterKP = wpimath.units.rotationsToRadians(0.1)
        self.shooterKS = wpimath.units.rotationsToRadians(0.1)
        self.shooterKV = wpimath.units.rotationsToRadians(0.1)

        # --- CAN Identification Numbers ---

        # Pigeon
        self.pigeonChannel = 5

        # Front Left Swerve Module
        self.frontLeftDriveMotorChannel = 10
        self.frontLeftTurningMotorChannel = 11
        self.frontLeftTurningEncoderChannel = 12

        # Front Right Swerve Module
        self.frontRightDriveMotorChannel = 14
        self.frontRightTurningMotorChannel = 15
        self.frontRightTurningEncoderChannel = 16

        # Back Left Swerve Module
        self.backLeftDriveMotorChannel = 18
        self.backLeftTurningMotorChannel = 19
        self.backLeftTurningEncoderChannel = 20

        # back Right Swerve Module
        self.backRightDriveMotorChannel = 22
        self.backRightTurningMotorChannel = 23
        self.backRightTurningEncoderChannel = 24

        # Shooter
        self.ShooterMotorChannelLeft = 34
        self.ShooterMotorChannelRight = 35

        # Elevator
        self.ElevatorMotorChannel = 36

        # Intake Balls
        self.BallIntakeMotorChannelLeft = 37
        self.BallIntakeMotorChannelRight = 38

        # Intake Arm
        self.IntakeArmMotorChannelLeft = 39
        self.IntakeArmMotorChannelRight = 40
        
        # PID For autonomous movement
        self.translationalPIDConstants = pathplannerlib.config.PIDConstants(5.0, 0.0, 0.0)
        self.rotationalPIDConstants = pathplannerlib.config.PIDConstants(5.0, 0.0, 0.0)

        # Physical Drive Constants
        self.driveBaseRadius = 2
        self.maxModuleSpeed = 2
        self.kMaxSpeed = 1  # 1 meters per second
        self.kMaxAngularSpeed = 1.25
        self.kWheelRadius = 0.0508
        self.kEncoderResolution = 4096
        self.kModuleMaxAngularVelocity = math.pi
        self.kModuleMaxAngularAcceleration = math.tau
        globalDistance = 0.635

        # Swerve Drive Module Locations (Autogenerated)
        self.frontLeftLocation = wpimath.geometry.Translation2d(globalDistance, globalDistance)
        self.frontRightLocation = wpimath.geometry.Translation2d(globalDistance, -globalDistance)
        self.backLeftLocation = wpimath.geometry.Translation2d(-globalDistance, globalDistance)
        self.backRightLocation = wpimath.geometry.Translation2d(-globalDistance, -globalDistance)
        self.swerveDriveKinematics = wpimath.kinematics.SwerveDrive4Kinematics(
            self.frontLeftLocation,
            self.frontRightLocation,
            self.backLeftLocation,
            self.backRightLocation
        )
